# Generated by Django 5.2.4 on 2025-07-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.IntegerField(default=600, help_text='Duration in seconds'),
            preserve_default=False,
        ),
    ]
