# Generated by Django 5.2.4 on 2025-07-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_match_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='rating_change',
            field=models.IntegerField(),
        ),
    ]
