# Generated by Django 5.2.4 on 2025-07-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='avatar',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='avatarfull',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='avatarmedium',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='profileurl',
            field=models.CharField(max_length=300),
        ),
    ]
