# Generated by Django 5.2.4 on 2025-07-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_steamuser_avatar_alter_steamuser_avatarfull_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='steamid32',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
